"""Export spaCy's English tokenizer data (en_core_web_sm 3.8) as C++ tables.

Run with the ModernBookNLP Python env (needs spaCy + en_core_web_sm):
  python gen_spacy_rules.py ../src

Writes spacy_en_special_cases.inc (entries {"<string>", "<tok1>\\x1f<tok2>..."}) and
spacy_en_classes.inc (the character classes of spaCy's affix regexes as codepoint ranges).
spaCy is MIT-licensed (see NOTICE).
"""
import re
import sys
from pathlib import Path

import spacy


def c_str(s: str) -> str:
    out = []
    for ch in s:
        if ch in '\\"':
            out.append("\\" + ch)
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20:
            out.append('\\x%02x""' % ord(ch))
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def ranges(pattern: str) -> list[tuple[int, int]]:
    rx = re.compile(pattern)
    out, start = [], None
    for cp in range(0x110000 + 1):
        hit = cp < 0x110000 and not (0xD800 <= cp <= 0xDFFF) and rx.fullmatch(chr(cp)) is not None
        if hit and start is None:
            start = cp
        elif not hit and start is not None:
            out.append((start, cp - 1))
            start = None
    return out


def classes() -> str:
    from spacy.lang.char_classes import (ALPHA, ALPHA_LOWER, ALPHA_UPPER, CONCAT_QUOTES, PUNCT,
                                         _other_symbols)
    defs = {
        "ALPHA": f"[{ALPHA}]",
        "ALPHA_LOWER": f"[{ALPHA_LOWER}]",
        "ALPHA_UPPER": f"[{ALPHA_UPPER}]",
        "ICONS": f"[{_other_symbols}]",
        # lookbehind of the "." suffix rule: [0-9{al}{e}{p}(?:{q})] (PUNCT/quotes merged into the class)
        "DOT_SUFFIX_AFTER": r"[0-9{al}{e}{p}(?:{q})]".format(
            al=ALPHA_LOWER, e=r"%²\-\+", q=CONCAT_QUOTES, p=PUNCT),
    }
    out = []
    for name, pat in defs.items():
        body = ",".join(f"{{0x{a:X},0x{b:X}}}" for a, b in ranges(pat))
        out.append(f"static const CpRange k{name}[] = {{{body}}};")
    return "\n".join(out)


def main():
    nlp = spacy.load("en_core_web_sm", disable=["ner", "parser", "tagger", "lemmatizer", "attribute_ruler"])
    rules = nlp.tokenizer.rules
    lines = [f"// generated by gen_spacy_rules.py from spaCy {spacy.__version__} / en_core_web_sm "
             f"{nlp.meta['version']} ({len(rules)} special cases)"]
    for key in sorted(rules):
        orths = [t[65] if isinstance(t, dict) and 65 in t else t["ORTH"] for t in rules[key]]
        lines.append("{%s, %s}," % (c_str(key), c_str("\x1f".join(orths))))
    out = Path(sys.argv[1])
    (out / "spacy_en_special_cases.inc").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    (out / "spacy_en_classes.inc").write_text(
        f"// generated by gen_spacy_rules.py from spaCy {spacy.__version__}\n" + classes() + "\n",
        encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
